// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<int> Result;

[numthreads(2,2,2)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    Result[id.x + id.y * 4 + id.z * 4 * 4] = id.x + id.y * 4 + id.z * 4 * 4;
}
